# EDA (Análise Exploratória de Dados) #

### Descritivos ###

Na maioria dos casos, os dados reais apresentam problemas como valores ausentes, dados duplicados ou inconsistentes. 

A qualidade dos dados é um fator crucial para o sucesso da análise, e a EDA é especialmente útil para identificar e resolver essas questões.

A limpeza de dados envolve várias etapas, como:

- Tratamento de dados ausentes;
- Remoção de duplicatas;
- Correção de inconsistências;
- Conversão de tipos de dados.

### SQLite ###

In [2]:
import sqlite3 as sql
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# Conexao com o banco de dados SQLite
def connect_db():
    try:
        # Modo rw garante que o arquivo farmavida.db já existe na pasta atual
        con = sql.connect('file:../database/farmavida.db?mode=rw', uri=True)
        print('Conexão com o banco de dados estabelecida com sucesso!')
        return con
    except sql.OperationalError:
        print('Erro: O arquivo "farmavida.db" não foi encontrado no diretório.')
        return None
    except Exception as e:
        print(f'Erro ao conectar ao banco de dados: {e}')
        return None

# Chamada da função
con = connect_db()
cur = con.cursor()

Conexão com o banco de dados estabelecida com sucesso!

In [4]:
table = [
    'cidades', 'clientes', 'comissoes', 
    'custo_produto','devolucoes', 'lojas', 
    'metas_vendedor', 'produtos', 'vendas','vendedores'
]

In [5]:
# Carregando os dados das tabelas para um DataFrame
for f in table:
    query = cur.execute('select * from {}'.format(f))
    df = pd.DataFrame(query.fetchall(), columns=[i[0] for i in query.description])
    print(f'\n--- Tabela {f} ---')
    display(df.head(5))

--- Tabela cidades ---

,cidade_uf,cidade,uf,regiao,latitude,longitude,populacao_estimada
0,São Paulo-SP,São Paulo,SP,Sudeste,-23.5505,-46.6333,11450000
1,Rio de Janeiro-RJ,Rio de Janeiro,RJ,Sudeste,-22.9068,-43.1729,6211000
2,Belo Horizonte-MG,Belo Horizonte,MG,Sudeste,-19.9167,-43.9345,2316000
3,Curitiba-PR,Curitiba,PR,Sul,-25.4284,-49.2733,1773000
4,Porto Alegre-RS,Porto Alegre,RS,Sul,-30.0346,-51.2177,1332000

--- Tabela clientes ---

,cod_cliente,nome_cliente,tipo_pessoa,segmento_pj,cidade_uf,data_cadastro
0,1,Fernanda Moreira Mendes,PF,NaN,Vitória-ES,2024-01-19
1,2,Olívia Monteiro Araújo,PF,NaN,Belém-PA,2024-07-22
2,3,Denise Ferreira Rocha,PF,NaN,Ribeirão Preto-SP,2020-01-17
3,4,Felipe Lima Gomes,PF,NaN,Londrina-PR,2018-10-15
4,5,Cláudio Almeida Mendes,PF,NaN,São Paulo-SP,2022-05-31

--- Tabela comissoes ---

   cod_vendedor data_inicio    data_fim  perc_comissao
0             1  2022-11-01  2024-05-21           4.08
1             1  2024-05-22         NaN           4.40
2             2  2022-01-01         NaN           3.38
3             3  2022-01-01  2024-05-10           3.57
4             3  2024-05-11         NaN           4.07

--- Tabela custo_produto ---

  cod_produto_ref   ano  mes  custo_unitario
0        MED-0001  2023    1            2.31
1        MED-0001  2023    2            2.32
2        MED-0001  2023    3            2.37
3        MED-0001  2023    4            2.52
4        MED-0001  2023    5            2.57

--- Tabela devolucoes ---

,id_devolucao,id_venda,data_devolucao,quantidade_devolvida,motivo
0,1,201,2023-01-03,2,Desistência
1,2,460,2023-01-03,1,Desistência
2,3,477,2023-01-03,1,Troca por outro produto
3,4,417,2023-01-04,1,Produto com defeito
4,5,211,2023-01-05,1,Produto vencido/avariado

--- Tabela lojas ---

,cod_loja,nome_loja,canal,cidade,uf,data_inauguracao,data_encerramento
0,1,FarmaVida São Paulo - Paulista,Loja Física,São Paulo,SP,NaN,NaN
1,2,FarmaVida São Paulo - Shopping Ibirapuera,Loja Física,São Paulo,SP,NaN,NaN
2,3,FarmaVida Rio de Janeiro - Centro,Loja Física,Rio de Janeiro,RJ,NaN,NaN
3,4,FarmaVida Rio de Janeiro - Barra,Loja Física,Rio de Janeiro,RJ,NaN,NaN
4,5,FarmaVida Belo Horizonte,Loja Física,Belo Horizonte,MG,NaN,NaN

--- Tabela metas_vendedor ---

   cod_vendedor   ano  mes  meta_receita_liquida
0             1  2023    1                7170.0
1             1  2023    2                7230.0
2             1  2023    3                7290.0
3             1  2023    4                6860.0
4             1  2023    5                6870.0

--- Tabela produtos ---

,cod_produto,nome_produto,categoria,subcategoria,tipo_medicamento,marca
0,1,Dipirona 500mg 10cp,Medicamentos,Analgésicos e Antitérmicos,Genérico,Medley
1,2,Dipirona 1g 10cp,Medicamentos,Analgésicos e Antitérmicos,Genérico,EMS
2,3,Paracetamol 750mg 20cp,Medicamentos,Analgésicos e Antitérmicos,Genérico,EMS
3,4,Analgex Dipirona 1g 10cp,Medicamentos,Analgésicos e Antitérmicos,Referência,Analgex
4,5,Termoflex Paracetamol 750mg 20cp,Medicamentos,Analgésicos e Antitérmicos,Referência,Termoflex

--- Tabela vendas ---

,id_venda,data_venda,cod_loja,num_nota_fiscal,cod_vendedor,cod_cliente,cod_produto,quantidade,valor_unitario,perc_desconto
0,1,2023-01-01,2,1,6,15128,58,2,24.9,0
1,2,2023-01-01,2,2,4,14820,82,2,39.9,0
2,3,2023-01-01,2,2,4,14820,106,2,49.9,0
3,4,2023-01-01,2,2,4,14820,37,2,12.9,0
4,5,2023-01-01,2,2,4,14820,66,5,49.9,8

--- Tabela vendedores ---

,cod_vendedor,nome_vendedor,canal,cod_loja,data_admissao,data_desligamento
0,1,Olívia Santos Fernandes,Loja Física,1,2022-11-01,NaN
1,2,Leonardo Almeida Lima,Loja Física,1,2018-10-01,NaN
2,3,Nicolas Teixeira Ferreira,Loja Física,1,2017-07-01,NaN
3,4,Elaine Oliveira Santos,Loja Física,2,2019-03-01,NaN
4,5,Lucas Carvalho Almeida,Loja Física,2,2017-07-01,NaN

In [6]:
# Fechando a conexão com o banco de dados
con.close()

### Exploração ###

In [7]:
df_cidades = pd.read_csv('../csv/cidades.csv', sep=';') #pd.DataFrame(cur.execute('select * from cidades').fetchall(), columns=[i[0] for i in cur.description])
df_clientes = pd.read_csv('../csv/clientes.csv', sep=';') #pd.DataFrame(cur.execute('select * from clientes').fetchall(), columns=[i[0] for i in cur.description])
df_comissoes = pd.read_csv('../csv/comissoes.csv', sep=';') #pd.DataFrame(cur.execute('select * from comissoes').fetchall(), columns=[i[0] for i in cur.description])
df_custo_produto = pd.read_csv('../csv/custo_produto.csv', sep=';') #pd.DataFrame(cur.execute('select * from custo_produto').fetchall(), columns=[i[0] for i in cur.description])
df_devolucoes = pd.read_csv('../csv/devolucoes.csv', sep=';') #pd.DataFrame(cur.execute('select * from devolucoes').fetchall(), columns=[i[0] for i in cur.description])
df_lojas = pd.read_csv('../csv/lojas.csv', sep=';') #pd.DataFrame(cur.execute('select * from lojas').fetchall(), columns=[i[0] for i in cur.description])
df_metas_vendedor = pd.read_csv('../csv/metas_vendedor.csv', sep=';') #pd.DataFrame(cur.execute('select * from metas_vendedor').fetchall(), columns=[i[0] for i in cur.description])
df_produtos = pd.read_csv('../csv/produtos.csv', sep=';') #pd.DataFrame(cur.execute('select * from produtos').fetchall(), columns=[i[0] for i in cur.description])
df_vendas = pd.read_csv('../csv/vendas.csv', sep=';') #pd.DataFrame(cur.execute('select * from vendas').fetchall(), columns=[i[0] for i in cur.description])
df_vendedores = pd.read_csv('../csv/vendedores.csv', sep=';') #pd.DataFrame(cur.execute('select * from vendedores').fetchall(), columns=[i[0] for i in cur.description])

### Linhas e Colunas ###

In [8]:
# Linhas e colunas
for i in table:
    datasets = eval(f'df_{i}')
    
    linhas_colunas = datasets.shape
    print(f'{i}: {linhas_colunas[0]} linhas | {linhas_colunas[1]} colunas')

cidades: 50 linhas | 7 colunas
clientes: 29700 linhas | 6 colunas
comissoes: 156 linhas | 4 colunas
custo_produto: 3155 linhas | 4 colunas
devolucoes: 6488 linhas | 5 colunas
lojas: 32 linhas | 7 colunas
metas_vendedor: 1703 linhas | 4 colunas
produtos: 134 linhas | 6 colunas
vendas: 223853 linhas | 10 colunas
vendedores: 82 linhas | 6 colunas

### Info ###

In [9]:
# Informações de tipagem dos datasets
for i in table:
    datasets = eval(f'df_{i}')
    
    result_info = datasets.info()
    print(f'\n{i}: {result_info}')

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cidade_uf           50 non-null     str
 1   cidade              50 non-null     str
 2   uf                  50 non-null     str
 3   regiao              50 non-null     str
 4   latitude            50 non-null     float64
 5   longitude           50 non-null     float64
 6   populacao_estimada  50 non-null     int64
dtypes: float64(2), int64(1), str(4)
memory usage: 2.9 KB

cidades: None
<class 'pandas.DataFrame'>
RangeIndex: 29700 entries, 0 to 29699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_cliente    29700 non-null  int64
 1   nome_cliente   29700 non-null  str
 2   tipo_pessoa    29700 non-null  str
 3   segmento_pj    900 non-null    str
 4   cidade_uf      29700 non-null  str
 5   data_cadastro  29700 non-null  str
dtypes: int64(1), str(5)
memory usage: 1.4 MB

clientes: None
<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_vendedor   156 non-null    int64
 1   data_inicio    156 non-null    str
 2   data_fim       84 non-null     str
 3   perc_comissao  156 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 5.0 KB

comissoes: None
<class 'pandas.DataFrame'>
RangeIndex: 3155 entries, 0 to 3154
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cod_produto_ref  3155 non-null   str
 1   ano              3155 non-null   int64
 2   mes              3155 non-null   int64
 3   custo_unitario   3155 non-null   float64
dtypes: float64(1), int64(2), str(1)
memory usage: 98.7 KB

custo_produto: None
<class 'pandas.DataFrame'>
RangeIndex: 6488 entries, 0 to 6487
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_devolucao          6488 non-null   int64
 1   id_venda              6488 non-null   int64
 2   data_devolucao        6488 non-null   str
 3   quantidade_devolvida  6488 non-null   int64
 4   motivo                6488 non-null   str
dtypes: int64(3), str(2)
memory usage: 253.6 KB

devolucoes: None
<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cod_loja           32 non-null     int64
 1   nome_loja          32 non-null     str
 2   canal              32 non-null     str
 3   cidade             32 non-null     str
 4   uf                 32 non-null     str
 5   data_inauguracao   2 non-null      str
 6   data_encerramento  1 non-null      str
dtypes: int64(1), str(6)
memory usage: 1.9 KB

lojas: None
<class 'pandas.DataFrame'>
RangeIndex: 1703 entries, 0 to 1702
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cod_vendedor          1703 non-null   int64
 1   ano                   1703 non-null   int64
 2   mes                   1703 non-null   int64
 3   meta_receita_liquida  1703 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 53.3 KB

metas_vendedor: None
<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cod_produto       134 non-null    int64
 1   nome_produto      134 non-null    str
 2   categoria         134 non-null    str
 3   subcategoria      134 non-null    str
 4   tipo_medicamento  134 non-null    str
 5   marca             134 non-null    str
dtypes: int64(1), str(5)
memory usage: 6.4 KB

produtos: None
<class 'pandas.DataFrame'>
RangeIndex: 223853 entries, 0 to 223852
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_venda         223853 non-null  int64
 1   data_venda       223853 non-null  str
 2   cod_loja         223853 non-null  int64
 3   num_nota_fiscal  223853 non-null  int64
 4   cod_vendedor     223853 non-null  int64
 5   cod_cliente      223853 non-null  int64
 6   cod_produto      223853 non-null  int64
 7   quantidade       223853 non-null  int64
 8   valor_unitario   223853 non-null  float64
 9   perc_desconto    223853 non-null  int64
dtypes: float64(1), int64(8), str(1)
memory usage: 17.1 MB

vendas: None
<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cod_vendedor       82 non-null     int64
 1   nome_vendedor      82 non-null     str
 2   canal              82 non-null     str
 3   cod_loja           82 non-null     int64
 4   data_admissao      82 non-null     str
 5   data_desligamento  10 non-null     str
dtypes: int64(2), str(4)
memory usage: 4.0 KB

vendedores: None

In [10]:
# Corrigindo a tipagem de dados
df_clientes['data_cadastro'] = pd.to_datetime(df_clientes['data_cadastro'], format='%Y-%m-%d')
df_comissoes['data_inicio'] = pd.to_datetime(df_comissoes['data_inicio'], format='%Y-%m-%d')
df_comissoes['data_fim'] = pd.to_datetime(df_comissoes['data_fim'], format='%Y-%m-%d')
df_devolucoes['data_devolucao'] = pd.to_datetime(df_devolucoes['data_devolucao'], format='%Y-%m-%d')
df_lojas['data_inauguracao'] = pd.to_datetime(df_lojas['data_inauguracao'], format='%Y-%m-%d')
df_lojas['data_encerramento'] = pd.to_datetime(df_lojas['data_encerramento'], format='%Y-%m-%d')
df_vendas['data_venda'] = pd.to_datetime(df_vendas['data_venda'], format = '%Y-%m-%d')
df_vendedores['data_admissao'] = pd.to_datetime(df_vendedores['data_admissao'], format = '%Y-%m-%d')
df_vendedores['data_desligamento'] = pd.to_datetime(df_vendedores['data_desligamento'], format = '%Y-%m-%d')
# df_custo_produto['cod_produto_ref'] = df_custo_produto['cod_produto_ref'].astype('Int64')

### Valores nulos ###

In [11]:
# Valores Nulos
for i in table:
    datasets = eval(f'df_{i}')
    
    result_nulos = datasets.isnull().any().any()
    print(f'{i}: {result_nulos}')

cidades: False
clientes: True
comissoes: True
custo_produto: False
devolucoes: False
lojas: True
metas_vendedor: False
produtos: False
vendas: False
vendedores: True

In [12]:
df_clientes.isnull().any()
# <>>> Remover os registros nulos? Pensar o que fazer! <<<>

cod_cliente      False
nome_cliente     False
tipo_pessoa      False
segmento_pj       True
cidade_uf        False
data_cadastro    False
dtype: bool

In [13]:
df_comissoes.isnull().any()
# <>>> O campo [data_fim] nulo indica que a comissão ainda não foi concluída <<<>

cod_vendedor     False
data_inicio      False
data_fim          True
perc_comissao    False
dtype: bool

In [14]:
df_lojas.isnull().any()
# <>>> Os campos [data_inauguração] e [data_encerramento] ser nulos pode ser regra de negócio <<<>

cod_loja             False
nome_loja            False
canal                False
cidade               False
uf                   False
data_inauguracao      True
data_encerramento     True
dtype: bool

In [15]:
df_vendedores.isnull().any()
# <>>> Quando a coluna [data_desligamento] é nula entende-se que o vendedor ainda está ativo <<<>

cod_vendedor         False
nome_vendedor        False
canal                False
cod_loja             False
data_admissao        False
data_desligamento     True
dtype: bool

### Valores Duplicados ###

In [16]:
# Valores Duplicados
for i in table:
    datasets = eval(f'df_{i}')
    
    result_duplicados = datasets.duplicated().any()
    print(f'{i}: {result_duplicados}')

cidades: False
clientes: False
comissoes: False
custo_produto: False
devolucoes: False
lojas: False
metas_vendedor: False
produtos: False
vendas: False
vendedores: False

In [17]:
# Distribuiçao
freq_cidades = df_cidades.groupby('cidade')['populacao_estimada'].sum()
freq_cidades.sort_values(ascending=False).head(5)

cidade
São Paulo         11450000
Rio de Janeiro     6211000
Brasília           2817000
Fortaleza          2428000
Salvador           2418000
Name: populacao_estimada, dtype: int64

In [18]:
df_clientes.isnull().any()

cod_cliente      False
nome_cliente     False
tipo_pessoa      False
segmento_pj       True
cidade_uf        False
data_cadastro    False
dtype: bool

<>>>> Tratar a serie segmento_pj <<<>

In [19]:
# Valores Duplicados
result = df_clientes.duplicated().any() 
print(f'Não há valores duplicados ({result})')

Não há valores duplicados (False)

In [20]:
# Estatística Descritiva
df_clientes.describe().T

,count,mean,min,25%,50%,75%,max,std
cod_cliente,29700.0,14850.5,1.0,7425.75,14850.5,22275.25,29700.0,8573.795834
data_cadastro,29700,2022-05-17 13:45:09.818181,2017-01-01 00:00:00,2020-08-25 18:00:00,2023-02-25 00:00:00,2024-02-27 00:00:00,2024-12-30 00:00:00,NaN

In [21]:
# Linhas e Colunas
print(f'Neste presente dataframe {table[2]} temos {df_comissoes.shape[0]} linhas e {df_comissoes.shape[1]} colunas')

Neste presente dataframe comissoes temos 156 linhas e 4 colunas

In [22]:
# informações (Tipagem)
df_comissoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_vendedor   156 non-null    int64
 1   data_inicio    156 non-null    datetime64[us]
 2   data_fim       84 non-null     datetime64[us]
 3   perc_comissao  156 non-null    float64
dtypes: datetime64[us](2), float64(1), int64(1)
memory usage: 5.0 KB

In [23]:
df_comissoes['data_inicio'] = pd.to_datetime(df_comissoes['data_inicio'], format='%Y-%m-%d')
df_comissoes['data_fim'] = pd.to_datetime(df_comissoes['data_fim'], format='%Y-%m-%d')

In [24]:
df_comissoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_vendedor   156 non-null    int64
 1   data_inicio    156 non-null    datetime64[us]
 2   data_fim       84 non-null     datetime64[us]
 3   perc_comissao  156 non-null    float64
dtypes: datetime64[us](2), float64(1), int64(1)
memory usage: 5.0 KB

In [25]:
# Valores nulos
result_null = df_comissoes.isnull().any().any()
if result_null == True:
    print(f'Existem series com valores nulos no DataFrame, result: ({result_null})')
else:
    print(f'Não há series com valores nulos no DataFrame, result: ({result_null})')

Existem series com valores nulos no DataFrame, result: (True)

In [26]:
df_comissoes.isnull().any()

cod_vendedor     False
data_inicio      False
data_fim          True
perc_comissao    False
dtype: bool

<>>>> Devido a regra de negócio a serie data_fim não precisa ter todos os registros preenchidos <<<<>

In [27]:
# Valores Duplicados
result = df_comissoes.duplicated().any() 
print(f'Não há valores duplicados ({result})')

Não há valores duplicados (False)

In [28]:
# Estatística Descritiva
df_comissoes.describe().T

,count,mean,min,25%,50%,75%,max,std
cod_vendedor,156.0,40.012821,1.0,21.0,40.0,59.0,82.0,22.603736
data_inicio,156,2023-03-03 10:27:41.538461,2022-01-01 00:00:00,2022-01-01 00:00:00,2023-05-17 12:00:00,2024-03-02 18:00:00,2024-11-30 00:00:00,NaN
data_fim,84,2024-01-17 01:42:51.428571,2023-02-02 00:00:00,2023-08-14 00:00:00,2024-01-24 00:00:00,2024-06-10 00:00:00,2024-11-29 00:00:00,NaN
perc_comissao,156.0,3.875128,1.24,3.56,4.11,4.5575,6.28,1.028768

In [29]:
# Linhas e Colunas
print(f'Neste presente dataframe {table[3]} temos {df_custo_produto.shape[0]} linhas e {df_custo_produto.shape[1]} colunas')

Neste presente dataframe custo_produto temos 3155 linhas e 4 colunas

In [30]:
# Valores Duplicados
result = df_custo_produto.duplicated().any() 
print(f'Não há valores duplicados ({result})')

Não há valores duplicados (False)

### Estatíticas Descritiva ###

In [31]:
# Describe
for i in table:
    datasets = eval(f'df_{i}')
    
    result_describe = datasets.describe()
    print(f'\n{i}: {result_describe}')

cidades:         latitude  longitude  populacao_estimada
count  50.000000  50.000000        5.000000e+01
mean  -16.397728 -46.558290        1.207260e+06
std     8.715509   7.274736        1.769910e+06
min   -30.034600 -67.824300        2.780000e+05
25%   -23.445475 -49.215125        4.465000e+05
50%   -19.417650 -46.712500        7.055000e+05
75%    -8.987350 -43.120925        1.253000e+06
max     2.823500 -34.861000        1.145000e+07

clientes:         cod_cliente               data_cadastro
count  29700.000000                       29700
mean   14850.500000  2022-05-17 13:45:09.818181
min        1.000000         2017-01-01 00:00:00
25%     7425.750000         2020-08-25 18:00:00
50%    14850.500000         2023-02-25 00:00:00
75%    22275.250000         2024-02-27 00:00:00
max    29700.000000         2024-12-30 00:00:00
std     8573.795834                         NaN

comissoes:        cod_vendedor                 data_inicio                    data_fim  \
count    156.000000                         156                          84
mean      40.012821  2023-03-03 10:27:41.538461  2024-01-17 01:42:51.428571
min        1.000000         2022-01-01 00:00:00         2023-02-02 00:00:00
25%       21.000000         2022-01-01 00:00:00         2023-08-14 00:00:00
50%       40.000000         2023-05-17 12:00:00         2024-01-24 00:00:00
75%       59.000000         2024-03-02 18:00:00         2024-06-10 00:00:00
max       82.000000         2024-11-30 00:00:00         2024-11-29 00:00:00
std       22.603736                         NaN                         NaN

       perc_comissao
count     156.000000
mean        3.875128
min         1.240000
25%         3.560000
50%         4.110000
75%         4.557500
max         6.280000
std         1.028768

custo_produto:                ano          mes  custo_unitario
count  3155.000000  3155.000000     3155.000000
mean   2023.498257     6.496989       19.166086
std       0.500076     3.460655       23.274165
min    2023.000000     1.000000        1.340000
25%    2023.000000     3.000000        5.065000
50%    2023.000000     6.000000       10.440000
75%    2024.000000    10.000000       22.415000
max    2024.000000    12.000000      164.000000

devolucoes:        id_devolucao       id_venda              data_devolucao  \
count   6488.000000    6488.000000                        6488
mean    3244.500000  129108.025894  2024-04-01 09:08:52.675709
min        1.000000     201.000000         2023-01-03 00:00:00
25%     1622.750000   76195.000000         2023-10-15 00:00:00
50%     3244.500000  140984.500000         2024-05-23 00:00:00
75%     4866.250000  184046.000000         2024-10-03 00:00:00
max     6488.000000  223542.000000         2025-01-24 00:00:00
std     1873.068605   64278.616060                         NaN

       quantidade_devolvida
count           6488.000000
mean               1.619451
min                1.000000
25%                1.000000
50%                1.000000
75%                2.000000
max               16.000000
std                1.199881

lojas:         cod_loja     data_inauguracao    data_encerramento
count  32.000000                    2                    1
mean   16.500000  2024-05-08 00:00:00  2024-06-30 00:00:00
min     1.000000  2024-03-01 00:00:00  2024-06-30 00:00:00
25%     8.750000  2024-04-04 00:00:00  2024-06-30 00:00:00
50%    16.500000  2024-05-08 00:00:00  2024-06-30 00:00:00
75%    24.250000  2024-06-11 00:00:00  2024-06-30 00:00:00
max    32.000000  2024-07-15 00:00:00  2024-06-30 00:00:00
std     9.380832                  NaN                  NaN

metas_vendedor:        cod_vendedor          ano          mes  meta_receita_liquida
count   1703.000000  1703.000000  1703.000000           1703.000000
mean      38.884909  2023.504991     6.516735           8393.024075
std       22.723746     0.500122     3.448230           6907.878909
min        1.000000  2023.000000     1.000000           1870.000000
25%       19.000000  2023.000000     4.000000           3830.000000
50%       38.000000  2024.000000     7.000000           6160.000000
75%       57.000000  2024.000000    10.000000           9210.000000
max       82.000000  2024.000000    12.000000          33940.000000

produtos:        cod_produto
count   134.000000
mean     67.500000
std      38.826537
min       1.000000
25%      34.250000
50%      67.500000
75%     100.750000
max     134.000000

vendas:             id_venda                  data_venda       cod_loja  \
count  223853.000000                      223853  223853.000000
mean   111927.000000  2024-01-26 23:01:21.519569      19.600591
min         1.000000         2023-01-01 00:00:00       1.000000
25%     55964.000000         2023-07-27 00:00:00       8.000000
50%    111927.000000         2024-02-05 00:00:00      22.000000
75%    167890.000000         2024-08-02 00:00:00      30.000000
max    223853.000000         2024-12-31 00:00:00      32.000000
std     64620.939242                         NaN      11.171960

       num_nota_fiscal   cod_vendedor    cod_cliente    cod_produto  \
count    223853.000000  223853.000000  223853.000000  223853.000000
mean       3274.266894      43.954506   14927.519095      60.227779
min           1.000000       1.000000       1.000000       1.000000
25%         670.000000      19.000000    7542.000000      32.000000
50%        1437.000000      49.000000   14995.000000      52.000000
75%        4143.000000      66.000000   22231.000000      91.000000
max       16544.000000      82.000000   29700.000000     999.000000
std        3991.063355      25.043856    8534.059777      39.705246

          quantidade  valor_unitario  perc_desconto
count  223853.000000   223853.000000  223853.000000
mean        1.847445       37.329888       4.116925
min         1.000000        3.400000       0.000000
25%         1.000000       12.570000       0.000000
50%         1.000000       21.300000       0.000000
75%         2.000000       41.920000       8.000000
max        23.000000      243.820000      25.000000
std         1.430180       40.883734       5.498721

vendedores:        cod_vendedor   cod_loja               data_admissao  \
count     82.000000  82.000000                          82
mean      41.500000  17.304878  2020-05-29 07:01:27.804878
min        1.000000   1.000000         2016-01-01 00:00:00
25%       21.250000   9.000000         2018-09-01 00:00:00
50%       41.500000  17.000000         2020-06-16 00:00:00
75%       61.750000  27.000000         2022-04-15 18:00:00
max       82.000000  32.000000         2024-07-15 00:00:00
std       23.815261  10.112563                         NaN

         data_desligamento
count                   10
mean   2024-03-12 16:48:00
min    2023-07-06 00:00:00
25%    2023-11-26 06:00:00
50%    2024-05-24 12:00:00
75%    2024-06-25 00:00:00
max    2024-06-30 00:00:00
std                    NaN

### Relacionamentos ###

In [32]:
re_cliente = df_clientes.merge(df_vendas, on='cod_cliente', how='left')
re_cliente = re_cliente[['cod_cliente', 'id_venda', 'data_venda', 'quantidade']]
re_cliente.tail(7)

        cod_cliente  id_venda data_venda  quantidade
228515        29699  216339.0 2024-12-13         1.0
228516        29699  216340.0 2024-12-13         2.0
228517        29699  216341.0 2024-12-13         1.0
228518        29699  216342.0 2024-12-13         1.0
228519        29699  216343.0 2024-12-13         1.0
228520        29700  158882.0 2024-07-07         1.0
228521        29700  158883.0 2024-07-07         1.0

In [40]:
re_cidades = df_cidades.merge(df_lojas, on='cidade', how='left')
re_cidades = re_cidades[['cidade', 'regiao', 'cod_loja', 'nome_loja']]

re_cidades.tail(5)

            cidade        regiao  cod_loja nome_loja
50  Campina Grande      Nordeste       NaN       NaN
51         Caruaru      Nordeste       NaN       NaN
52        Anápolis  Centro-Oeste       NaN       NaN
53   Montes Claros       Sudeste       NaN       NaN
54      Petrópolis       Sudeste       NaN       NaN

In [33]:
re_produto = df_produtos.merge(df_custo_produto, left_on='cod_produto', right_on='cod_produto_ref', how='left')
re_produto = re_produto[['cod_produto', 'nome_produto', 'cod_produto_ref', 'custo_unitario']]
re_produto.head(5)

# Necessário criar um novo campo para relacionamento

ValueError: You are trying to merge on int64 and str columns for key 'cod_produto'. If you wish to proceed you should use pd.concat

## Conclusão ##