# EDA (Análise Exploratória de Dados) #

## Limpeza dos dados ## 

Na maioria dos casos, os dados reais apresentam problemas como valores ausentes, dados duplicados ou inconsistentes. 

A qualidade dos dados é um fator crucial para o sucesso da análise, e a EDA é especialmente útil para identificar e resolver essas questões.

A limpeza de dados envolve várias etapas, como:

- Tratamento de dados ausentes;
- Remoção de duplicatas;
- Correção de inconsistências;
- Conversão de tipos de dados.

In [50]:
import sqlite3 as sql
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def connect_db():
    try:
        # Modo rw garante que o arquivo farmavida.db já existe na pasta atual
        con = sql.connect('file:../database/farmavida.db?mode=rw', uri=True)
        print('Conexão com o banco de dados estabelecida com sucesso!')
        return con
    except sql.OperationalError:
        print('Erro: O arquivo "farmavida.db" não foi encontrado no diretório.')
        return None
    except Exception as e:
        print(f'Erro ao conectar ao banco de dados: {e}')
        return None

# Chamada da função
con = connect_db()

Conexão com o banco de dados estabelecida com sucesso!

## Tables ##

### Cidades ###

In [44]:
# Carregando os dados da tabela 'cidades' para um DataFrame
query = cur.execute('select * from {}'.format(table[0]))
df_cidades = pd.DataFrame(query.fetchall(), columns=[i[0] for i in query.description])
df_cidades.head(5)

,cidade_uf,cidade,uf,regiao,latitude,longitude,populacao_estimada
0,São Paulo-SP,São Paulo,SP,Sudeste,-23.5505,-46.6333,11450000
1,Rio de Janeiro-RJ,Rio de Janeiro,RJ,Sudeste,-22.9068,-43.1729,6211000
2,Belo Horizonte-MG,Belo Horizonte,MG,Sudeste,-19.9167,-43.9345,2316000
3,Curitiba-PR,Curitiba,PR,Sul,-25.4284,-49.2733,1773000
4,Porto Alegre-RS,Porto Alegre,RS,Sul,-30.0346,-51.2177,1332000

In [36]:
# Informações sobre o DataFrame df_cidades
print(f'Neste presente dataframe temos {df_cidades.shape[0]} linhas e {df_cidades.shape[1]} colunas')

Neste presente dataframe temos 50 linhas e 7 colunas

In [28]:
# informações sobre o DataFrame df_cidades (Tipagem)
df_cidades.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cidade_uf           50 non-null     str
 1   cidade              50 non-null     str
 2   uf                  50 non-null     str
 3   regiao              50 non-null     str
 4   latitude            50 non-null     float64
 5   longitude           50 non-null     float64
 6   populacao_estimada  50 non-null     int64
dtypes: float64(2), int64(1), str(4)
memory usage: 2.9 KB

In [48]:
df_cidades.describe().T

,count,mean,std,min,25%,50%,75%,max
latitude,50.0,-1.639773e+01,8.715509e+00,-30.0346,-23.445475,-19.41765,-8.987350e+00,2.823500e+00
longitude,50.0,-4.655829e+01,7.274736e+00,-67.8243,-49.215125,-46.71250,-4.312092e+01,-3.486100e+01
populacao_estimada,50.0,1.207260e+06,1.769910e+06,278000.0000,446500.000000,705500.00000,1.253000e+06,1.145000e+07

In [26]:
# Verificando se há valores nulos no DataFrame df_cidades
df_cidades.isnull().any()

cidade_uf             False
cidade                False
uf                    False
regiao                False
latitude              False
longitude             False
populacao_estimada    False
dtype: bool

In [43]:
result = df_cidades.duplicated().any()
print(f'Não temos valores duplicados ({result})')

Não temos valores duplicados (False)

In [60]:
freq_cidades = df_cidades.groupby('cidade')['populacao_estimada'].sum()
freq_cidades.sort_values(ascending=False).head(10)

cidade
São Paulo         11450000
Rio de Janeiro     6211000
Brasília           2817000
Fortaleza          2428000
Salvador           2418000
Belo Horizonte     2316000
Manaus             2063000
Curitiba           1773000
Recife             1488000
Goiânia            1437000
Name: populacao_estimada, dtype: int64

### Clientes ###

In [61]:
# Fechando a conexão com o banco de dados
con.close()

## Conclusão ##

## Análise de Correlação ##