# EDA (Análise Exploratória de Dados) #

### Descritivos ###

Na maioria dos casos, os dados reais apresentam problemas como valores ausentes, dados duplicados ou inconsistentes. 

A qualidade dos dados é um fator crucial para o sucesso da análise, e a EDA é especialmente útil para identificar e resolver essas questões.

A limpeza de dados envolve várias etapas, como:

- Tratamento de dados ausentes;
- Remoção de duplicatas;
- Correção de inconsistências;
- Conversão de tipos de dados.

### Exploração ###

In [51]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [52]:
table = [
    'cidades', 'clientes', 'comissoes', 
    'custo_produto','devolucoes', 'lojas', 
    'metas_vendedor', 'produtos', 'vendas','vendedores'
]

In [53]:
df_cidades = pd.read_csv('../csv/cidades.csv', sep=';') 
df_clientes = pd.read_csv('../csv/clientes.csv', sep=';') 
df_comissoes = pd.read_csv('../csv/comissoes.csv', sep=';') 
df_custo_produto = pd.read_csv('../csv/custo_produto.csv', sep=';') 
df_devolucoes = pd.read_csv('../csv/devolucoes.csv', sep=';') 
df_lojas = pd.read_csv('../csv/lojas.csv', sep=';') 
df_metas_vendedor = pd.read_csv('../csv/metas_vendedor.csv', sep=';') 
df_produtos = pd.read_csv('../csv/produtos.csv', sep=';') 
df_vendas = pd.read_csv('../csv/vendas.csv', sep=';') 
df_vendedores = pd.read_csv('../csv/vendedores.csv', sep=';')

### Linhas e Colunas ###

In [54]:
# Linhas e colunas
for i in table:
    datasets = eval(f'df_{i}')
    
    linhas_colunas = datasets.shape
    print(f'{i}: {linhas_colunas[0]} linhas | {linhas_colunas[1]} colunas')

cidades: 50 linhas | 7 colunas
clientes: 29700 linhas | 6 colunas
comissoes: 156 linhas | 4 colunas
custo_produto: 3155 linhas | 4 colunas
devolucoes: 6488 linhas | 5 colunas
lojas: 32 linhas | 7 colunas
metas_vendedor: 1703 linhas | 4 colunas
produtos: 134 linhas | 6 colunas
vendas: 223853 linhas | 10 colunas
vendedores: 82 linhas | 6 colunas

### Info ###

In [55]:
# Informações de tipagem dos datasets
for i in table:
    datasets = eval(f'df_{i}')
    
    result_info = datasets.info()
    print(f'\n{i}: {result_info}')

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cidade_uf           50 non-null     str
 1   cidade              50 non-null     str
 2   uf                  50 non-null     str
 3   regiao              50 non-null     str
 4   latitude            50 non-null     float64
 5   longitude           50 non-null     float64
 6   populacao_estimada  50 non-null     int64
dtypes: float64(2), int64(1), str(4)
memory usage: 2.9 KB

cidades: None
<class 'pandas.DataFrame'>
RangeIndex: 29700 entries, 0 to 29699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_cliente    29700 non-null  int64
 1   nome_cliente   29700 non-null  str
 2   tipo_pessoa    29700 non-null  str
 3   segmento_pj    900 non-null    str
 4   cidade_uf      29700 non-null  str
 5   data_cadastro  29700 non-null  str
dtypes: int64(1), str(5)
memory usage: 1.4 MB

clientes: None
<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_vendedor   156 non-null    int64
 1   data_inicio    156 non-null    str
 2   data_fim       84 non-null     str
 3   perc_comissao  156 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 5.0 KB

comissoes: None
<class 'pandas.DataFrame'>
RangeIndex: 3155 entries, 0 to 3154
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cod_produto_ref  3155 non-null   str
 1   ano              3155 non-null   int64
 2   mes              3155 non-null   int64
 3   custo_unitario   3155 non-null   float64
dtypes: float64(1), int64(2), str(1)
memory usage: 98.7 KB

custo_produto: None
<class 'pandas.DataFrame'>
RangeIndex: 6488 entries, 0 to 6487
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_devolucao          6488 non-null   int64
 1   id_venda              6488 non-null   int64
 2   data_devolucao        6488 non-null   str
 3   quantidade_devolvida  6488 non-null   int64
 4   motivo                6488 non-null   str
dtypes: int64(3), str(2)
memory usage: 253.6 KB

devolucoes: None
<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cod_loja           32 non-null     int64
 1   nome_loja          32 non-null     str
 2   canal              32 non-null     str
 3   cidade             32 non-null     str
 4   uf                 32 non-null     str
 5   data_inauguracao   2 non-null      str
 6   data_encerramento  1 non-null      str
dtypes: int64(1), str(6)
memory usage: 1.9 KB

lojas: None
<class 'pandas.DataFrame'>
RangeIndex: 1703 entries, 0 to 1702
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cod_vendedor          1703 non-null   int64
 1   ano                   1703 non-null   int64
 2   mes                   1703 non-null   int64
 3   meta_receita_liquida  1703 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 53.3 KB

metas_vendedor: None
<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cod_produto       134 non-null    int64
 1   nome_produto      134 non-null    str
 2   categoria         134 non-null    str
 3   subcategoria      134 non-null    str
 4   tipo_medicamento  134 non-null    str
 5   marca             134 non-null    str
dtypes: int64(1), str(5)
memory usage: 6.4 KB

produtos: None
<class 'pandas.DataFrame'>
RangeIndex: 223853 entries, 0 to 223852
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_venda         223853 non-null  int64
 1   data_venda       223853 non-null  str
 2   cod_loja         223853 non-null  int64
 3   num_nota_fiscal  223853 non-null  int64
 4   cod_vendedor     223853 non-null  int64
 5   cod_cliente      223853 non-null  int64
 6   cod_produto      223853 non-null  int64
 7   quantidade       223853 non-null  int64
 8   valor_unitario   223853 non-null  float64
 9   perc_desconto    223853 non-null  int64
dtypes: float64(1), int64(8), str(1)
memory usage: 17.1 MB

vendas: None
<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cod_vendedor       82 non-null     int64
 1   nome_vendedor      82 non-null     str
 2   canal              82 non-null     str
 3   cod_loja           82 non-null     int64
 4   data_admissao      82 non-null     str
 5   data_desligamento  10 non-null     str
dtypes: int64(2), str(4)
memory usage: 4.0 KB

vendedores: None

In [56]:
# Corrigindo a tipagem de dados
df_clientes['data_cadastro'] = pd.to_datetime(df_clientes['data_cadastro'], format='%Y-%m-%d')
df_comissoes['data_inicio'] = pd.to_datetime(df_comissoes['data_inicio'], format='%Y-%m-%d')
df_comissoes['data_fim'] = pd.to_datetime(df_comissoes['data_fim'], format='%Y-%m-%d')
df_devolucoes['data_devolucao'] = pd.to_datetime(df_devolucoes['data_devolucao'], format='%Y-%m-%d')
df_lojas['data_inauguracao'] = pd.to_datetime(df_lojas['data_inauguracao'], format='%Y-%m-%d')
df_lojas['data_encerramento'] = pd.to_datetime(df_lojas['data_encerramento'], format='%Y-%m-%d')
df_vendas['data_venda'] = pd.to_datetime(df_vendas['data_venda'], format = '%Y-%m-%d')
df_vendedores['data_admissao'] = pd.to_datetime(df_vendedores['data_admissao'], format = '%Y-%m-%d')
df_vendedores['data_desligamento'] = pd.to_datetime(df_vendedores['data_desligamento'], format = '%Y-%m-%d')
# df_custo_produto['cod_produto_ref'] = df_custo_produto['cod_produto_ref'].astype('Int64')

### Valores nulos ###

In [57]:
# Valores Nulos
for i in table:
    datasets = eval(f'df_{i}')
    
    result_nulos = datasets.isnull().any().any()
    print(f'{i}: {result_nulos}')

cidades: False
clientes: True
comissoes: True
custo_produto: False
devolucoes: False
lojas: True
metas_vendedor: False
produtos: False
vendas: False
vendedores: True

In [58]:
df_clientes.isnull().any()
# <>>> Remover os registros nulos? Pensar o que fazer! <<<>

cod_cliente      False
nome_cliente     False
tipo_pessoa      False
segmento_pj       True
cidade_uf        False
data_cadastro    False
dtype: bool

In [59]:
df_comissoes.isnull().any()
# <>>> O campo [data_fim] nulo indica que a comissão ainda não foi concluída <<<>

cod_vendedor     False
data_inicio      False
data_fim          True
perc_comissao    False
dtype: bool

In [60]:
df_lojas.isnull().any()
# <>>> Os campos [data_inauguração] e [data_encerramento] ser nulos pode ser regra de negócio <<<>

cod_loja             False
nome_loja            False
canal                False
cidade               False
uf                   False
data_inauguracao      True
data_encerramento     True
dtype: bool

In [61]:
df_vendedores.isnull().any()
# <>>> Quando a coluna [data_desligamento] é nula entende-se que o vendedor ainda está ativo <<<>

cod_vendedor         False
nome_vendedor        False
canal                False
cod_loja             False
data_admissao        False
data_desligamento     True
dtype: bool

### Valores Duplicados ###

In [62]:
# Valores Duplicados
for i in table:
    datasets = eval(f'df_{i}')
    
    result_duplicados = datasets.duplicated().any()
    print(f'{i}: {result_duplicados}')

cidades: False
clientes: False
comissoes: False
custo_produto: False
devolucoes: False
lojas: False
metas_vendedor: False
produtos: False
vendas: False
vendedores: False

In [63]:
# Distribuiçao
freq_cidades = df_cidades.groupby('cidade')['populacao_estimada'].sum()
freq_cidades.sort_values(ascending=False).head(5)

cidade
São Paulo         11450000
Rio de Janeiro     6211000
Brasília           2817000
Fortaleza          2428000
Salvador           2418000
Name: populacao_estimada, dtype: int64

In [64]:
df_clientes.isnull().any()

cod_cliente      False
nome_cliente     False
tipo_pessoa      False
segmento_pj       True
cidade_uf        False
data_cadastro    False
dtype: bool

<>>>> Tratar a serie segmento_pj <<<>

In [65]:
# Valores Duplicados
result = df_clientes.duplicated().any() 
print(f'Não há valores duplicados ({result})')

Não há valores duplicados (False)

In [66]:
# Estatística Descritiva
df_clientes.describe().T

,count,mean,min,25%,50%,75%,max,std
cod_cliente,29700.0,14850.5,1.0,7425.75,14850.5,22275.25,29700.0,8573.795834
data_cadastro,29700,2022-05-17 13:45:09.818181,2017-01-01 00:00:00,2020-08-25 18:00:00,2023-02-25 00:00:00,2024-02-27 00:00:00,2024-12-30 00:00:00,NaN

In [67]:
# Linhas e Colunas
print(f'Neste presente dataframe {table[2]} temos {df_comissoes.shape[0]} linhas e {df_comissoes.shape[1]} colunas')

Neste presente dataframe comissoes temos 156 linhas e 4 colunas

In [68]:
# informações (Tipagem)
df_comissoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_vendedor   156 non-null    int64
 1   data_inicio    156 non-null    datetime64[us]
 2   data_fim       84 non-null     datetime64[us]
 3   perc_comissao  156 non-null    float64
dtypes: datetime64[us](2), float64(1), int64(1)
memory usage: 5.0 KB

In [69]:
df_comissoes['data_inicio'] = pd.to_datetime(df_comissoes['data_inicio'], format='%Y-%m-%d')
df_comissoes['data_fim'] = pd.to_datetime(df_comissoes['data_fim'], format='%Y-%m-%d')

In [70]:
df_comissoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_vendedor   156 non-null    int64
 1   data_inicio    156 non-null    datetime64[us]
 2   data_fim       84 non-null     datetime64[us]
 3   perc_comissao  156 non-null    float64
dtypes: datetime64[us](2), float64(1), int64(1)
memory usage: 5.0 KB

In [71]:
# Valores nulos
result_null = df_comissoes.isnull().any().any()
if result_null == True:
    print(f'Existem series com valores nulos no DataFrame, result: ({result_null})')
else:
    print(f'Não há series com valores nulos no DataFrame, result: ({result_null})')

Existem series com valores nulos no DataFrame, result: (True)

In [72]:
df_comissoes.isnull().any()

cod_vendedor     False
data_inicio      False
data_fim          True
perc_comissao    False
dtype: bool

<>>>> Devido a regra de negócio a serie data_fim não precisa ter todos os registros preenchidos <<<<>

In [73]:
# Valores Duplicados
result = df_comissoes.duplicated().any() 
print(f'Não há valores duplicados ({result})')

Não há valores duplicados (False)

In [74]:
# Estatística Descritiva
df_comissoes.describe().T

,count,mean,min,25%,50%,75%,max,std
cod_vendedor,156.0,40.012821,1.0,21.0,40.0,59.0,82.0,22.603736
data_inicio,156,2023-03-03 10:27:41.538461,2022-01-01 00:00:00,2022-01-01 00:00:00,2023-05-17 12:00:00,2024-03-02 18:00:00,2024-11-30 00:00:00,NaN
data_fim,84,2024-01-17 01:42:51.428571,2023-02-02 00:00:00,2023-08-14 00:00:00,2024-01-24 00:00:00,2024-06-10 00:00:00,2024-11-29 00:00:00,NaN
perc_comissao,156.0,3.875128,1.24,3.56,4.11,4.5575,6.28,1.028768

In [75]:
# Linhas e Colunas
print(f'Neste presente dataframe {table[3]} temos {df_custo_produto.shape[0]} linhas e {df_custo_produto.shape[1]} colunas')

Neste presente dataframe custo_produto temos 3155 linhas e 4 colunas

In [76]:
# Valores Duplicados
result = df_custo_produto.duplicated().any() 
print(f'Não há valores duplicados ({result})')

Não há valores duplicados (False)

### Estatíticas Descritiva ###

In [77]:
# Describe
for i in table:
    datasets = eval(f'df_{i}')
    
    result_describe = datasets.describe()
    print(f'\n{i}: {result_describe}')

cidades:         latitude  longitude  populacao_estimada
count  50.000000  50.000000        5.000000e+01
mean  -16.397728 -46.558290        1.207260e+06
std     8.715509   7.274736        1.769910e+06
min   -30.034600 -67.824300        2.780000e+05
25%   -23.445475 -49.215125        4.465000e+05
50%   -19.417650 -46.712500        7.055000e+05
75%    -8.987350 -43.120925        1.253000e+06
max     2.823500 -34.861000        1.145000e+07

clientes:         cod_cliente               data_cadastro
count  29700.000000                       29700
mean   14850.500000  2022-05-17 13:45:09.818181
min        1.000000         2017-01-01 00:00:00
25%     7425.750000         2020-08-25 18:00:00
50%    14850.500000         2023-02-25 00:00:00
75%    22275.250000         2024-02-27 00:00:00
max    29700.000000         2024-12-30 00:00:00
std     8573.795834                         NaN

comissoes:        cod_vendedor                 data_inicio                    data_fim  \
count    156.000000                         156                          84
mean      40.012821  2023-03-03 10:27:41.538461  2024-01-17 01:42:51.428571
min        1.000000         2022-01-01 00:00:00         2023-02-02 00:00:00
25%       21.000000         2022-01-01 00:00:00         2023-08-14 00:00:00
50%       40.000000         2023-05-17 12:00:00         2024-01-24 00:00:00
75%       59.000000         2024-03-02 18:00:00         2024-06-10 00:00:00
max       82.000000         2024-11-30 00:00:00         2024-11-29 00:00:00
std       22.603736                         NaN                         NaN

       perc_comissao
count     156.000000
mean        3.875128
min         1.240000
25%         3.560000
50%         4.110000
75%         4.557500
max         6.280000
std         1.028768

custo_produto:                ano          mes  custo_unitario
count  3155.000000  3155.000000     3155.000000
mean   2023.498257     6.496989       19.166086
std       0.500076     3.460655       23.274165
min    2023.000000     1.000000        1.340000
25%    2023.000000     3.000000        5.065000
50%    2023.000000     6.000000       10.440000
75%    2024.000000    10.000000       22.415000
max    2024.000000    12.000000      164.000000

devolucoes:        id_devolucao       id_venda              data_devolucao  \
count   6488.000000    6488.000000                        6488
mean    3244.500000  129108.025894  2024-04-01 09:08:52.675709
min        1.000000     201.000000         2023-01-03 00:00:00
25%     1622.750000   76195.000000         2023-10-15 00:00:00
50%     3244.500000  140984.500000         2024-05-23 00:00:00
75%     4866.250000  184046.000000         2024-10-03 00:00:00
max     6488.000000  223542.000000         2025-01-24 00:00:00
std     1873.068605   64278.616060                         NaN

       quantidade_devolvida
count           6488.000000
mean               1.619451
min                1.000000
25%                1.000000
50%                1.000000
75%                2.000000
max               16.000000
std                1.199881

lojas:         cod_loja     data_inauguracao    data_encerramento
count  32.000000                    2                    1
mean   16.500000  2024-05-08 00:00:00  2024-06-30 00:00:00
min     1.000000  2024-03-01 00:00:00  2024-06-30 00:00:00
25%     8.750000  2024-04-04 00:00:00  2024-06-30 00:00:00
50%    16.500000  2024-05-08 00:00:00  2024-06-30 00:00:00
75%    24.250000  2024-06-11 00:00:00  2024-06-30 00:00:00
max    32.000000  2024-07-15 00:00:00  2024-06-30 00:00:00
std     9.380832                  NaN                  NaN

metas_vendedor:        cod_vendedor          ano          mes  meta_receita_liquida
count   1703.000000  1703.000000  1703.000000           1703.000000
mean      38.884909  2023.504991     6.516735           8393.024075
std       22.723746     0.500122     3.448230           6907.878909
min        1.000000  2023.000000     1.000000           1870.000000
25%       19.000000  2023.000000     4.000000           3830.000000
50%       38.000000  2024.000000     7.000000           6160.000000
75%       57.000000  2024.000000    10.000000           9210.000000
max       82.000000  2024.000000    12.000000          33940.000000

produtos:        cod_produto
count   134.000000
mean     67.500000
std      38.826537
min       1.000000
25%      34.250000
50%      67.500000
75%     100.750000
max     134.000000

vendas:             id_venda                  data_venda       cod_loja  \
count  223853.000000                      223853  223853.000000
mean   111927.000000  2024-01-26 23:01:21.519569      19.600591
min         1.000000         2023-01-01 00:00:00       1.000000
25%     55964.000000         2023-07-27 00:00:00       8.000000
50%    111927.000000         2024-02-05 00:00:00      22.000000
75%    167890.000000         2024-08-02 00:00:00      30.000000
max    223853.000000         2024-12-31 00:00:00      32.000000
std     64620.939242                         NaN      11.171960

       num_nota_fiscal   cod_vendedor    cod_cliente    cod_produto  \
count    223853.000000  223853.000000  223853.000000  223853.000000
mean       3274.266894      43.954506   14927.519095      60.227779
min           1.000000       1.000000       1.000000       1.000000
25%         670.000000      19.000000    7542.000000      32.000000
50%        1437.000000      49.000000   14995.000000      52.000000
75%        4143.000000      66.000000   22231.000000      91.000000
max       16544.000000      82.000000   29700.000000     999.000000
std        3991.063355      25.043856    8534.059777      39.705246

          quantidade  valor_unitario  perc_desconto
count  223853.000000   223853.000000  223853.000000
mean        1.847445       37.329888       4.116925
min         1.000000        3.400000       0.000000
25%         1.000000       12.570000       0.000000
50%         1.000000       21.300000       0.000000
75%         2.000000       41.920000       8.000000
max        23.000000      243.820000      25.000000
std         1.430180       40.883734       5.498721

vendedores:        cod_vendedor   cod_loja               data_admissao  \
count     82.000000  82.000000                          82
mean      41.500000  17.304878  2020-05-29 07:01:27.804878
min        1.000000   1.000000         2016-01-01 00:00:00
25%       21.250000   9.000000         2018-09-01 00:00:00
50%       41.500000  17.000000         2020-06-16 00:00:00
75%       61.750000  27.000000         2022-04-15 18:00:00
max       82.000000  32.000000         2024-07-15 00:00:00
std       23.815261  10.112563                         NaN

         data_desligamento
count                   10
mean   2024-03-12 16:48:00
min    2023-07-06 00:00:00
25%    2023-11-26 06:00:00
50%    2024-05-24 12:00:00
75%    2024-06-25 00:00:00
max    2024-06-30 00:00:00
std                    NaN

### Refinamento ###

**Checar as Chaves Primárias (Duplicadas nas Dimensões)**

In [78]:
# Já vimos que a linha inteira não é duplicada, mas vale conferir se os IDs são únicos:
# Devem todos retornar True (sem IDs repetidos)
 
print(f'Dimensão produtos: {df_produtos['cod_produto'].is_unique}') 
print(f'Dimensão clientes: {df_clientes['cod_cliente'].is_unique}') 
print(f'Dimensão vendedores: {df_vendedores['cod_vendedor'].is_unique}') 
print(f'Dimensão lojas: {df_lojas['cod_loja'].is_unique}')

Dimensão produtos: True
Dimensão clientes: True
Dimensão vendedores: True
Dimensão lojas: True

**Investigando as Chaves Orfãs em vendas**

In [79]:
# Vale rodar um filtro rápido para ver o tamanho do problema: 
# Lembra que no describe() o cod_produto em vendas chegou a 999, mas a tabela de produtos só tem 134?
# >>> (Uma venda apontando para um produto inexistente no catálogo) <<<

orfaos_prod = df_vendas[~df_vendas['cod_produto'].isin(df_produtos['cod_produto'])] 
print(f"Linhas de vendas com produto não cadastrado: {len(orfaos_prod)}")

Linhas de vendas com produto não cadastrado: 60

In [80]:
# Descobre quais códigos vendidos não existem no cadastro de produtos: 
codigos_nao_cadastrados = set(df_vendas['cod_produto']) - set(df_produtos['cod_produto']) 
print(f"Códigos de produtos em vendas que não existem na dimensão produtos: {codigos_nao_cadastrados}") 

# Quantidade de vendas afetadas: 
qtd_linhas_afetadas = df_vendas['cod_produto'].isin(codigos_nao_cadastrados).sum() 
print(f"Total de registros de vendas afetados: {qtd_linhas_afetadas}")

Códigos de produtos em vendas que não existem na dimensão produtos: {999}
Total de registros de vendas afetados: 60

**Planejar o Modelo de Dados (Star Schema)**

Ter em mente como você conectará as tabelas no Power BI:

- Tabelas Fato: vendas, devolucoes, metas_vendedor. 
- Tabelas Dimensão: clientes, produtos, vendedores, lojas, cidades e uma tabela d_Calendario (que você criará no Power BI). 
- Atenção ao custo_produto: O custo não é estático por produto, ele varia por ano e mes. 
- No Power BI será necessário mesclar o custo unitário direto na tabela vendas (via Power Query) usando uma chave composta (cod_produto + ano + mes) para poder calcular o Lucro.

## Conclusão ##

### 1. Qualidade e Integridade da Base

Volumetria: 10 tabelas auditadas a partir dos arquivos .csv, cobrindo mais de 223 mil registros de vendas
(período de 2023 a 2024).

Duplicatas: Nenhuma duplicata encontrada a nível de linha nas 10 tabelas analisadas.
Unicidade das Dimensões: As chaves primárias (cod_produto, cod_cliente, cod_vendedor, cod_loja) são
100% únicas (is_unique = True), garantindo relacionamentos 1:N no Power BI sem risco de cardinalidade muitos- para-muitos.

### 2. Validação das Regras de Negócio e Nulos

segmento_pj (clientes): 97% dos registros são nulos por corresponderem a clientes Pessoa Física (PF). Os
registros foram preservados para manter a totalidade da base.

data_fim (comissões) e data_desligamento (vendedores): Os valores nulos representam registros ativos
(comissões vigentes e colaboradores ativos).

data_encerramento (lojas): Nulos indicam lojas em plena operação comercial.
### 3. Ponto Crítico Identificado para o Power BI (Chaves Órfãs)

Foram detectadas 60 linhas de vendas associadas ao cod_produto = 999, código inexistente na dimensão
produtos (que possui itens de 1 a 134).

Ação no Power Query: Tratar essa chave criando uma linha/categoria para "Produto Não Cadastrado / Outros",
evitando que o Power BI gere agrupamentos em branco (Blank) nos visuais de produto e categoria.

### 4. Diretrizes para Modelagem Dimensional (Star Schema)

- Tabelas Fato: vendas, devolucoes, metas_vendedor.
- Tabelas Dimensão: produtos, clientes, vendedores, lojas, cidades e criação de d_Calendario via DAX (Power BI).